# Generated by Django 4.0.6 on 2022-07-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parentName', models.CharField(max_length=100)),
                ('parentNumber', models.CharField(max_length=10)),
                ('dateOfBirth', models.DateField(max_length=6)),
                ('teacherName', models.CharField(max_length=20)),
                ('gradeLevel', models.CharField(max_length=4)),
                ('roomNumber', models.CharField(max_length=4)),
                ('pickupMethod', models.CharField(max_length=20)),
                ('photo_url', models.TextField()),
            ],
        ),
    ]
