# Generated by Django 4.0.6 on 2022-07-08 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=4)),
                ('teacher_Name', models.CharField(max_length=100)),
                ('scholar_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_name', models.CharField(default='Jon Doe', max_length=50)),
                ('parent_Name', models.CharField(default='Jane Doe', max_length=100)),
                ('parent_Number', models.CharField(default='(516)123-4567', max_length=10)),
                ('date_Of_Birth', models.DateField(default='2012-11-11', max_length=10)),
                ('teacher_Name', models.CharField(default='Ms.Smikle', max_length=20)),
                ('grade_Level', models.CharField(default='4', max_length=4)),
                ('room_Number', models.CharField(default='110', max_length=4)),
                ('pickup_Method', models.CharField(default='Bus #280', max_length=20)),
                ('photo_url', models.TextField(default='https://tse2.mm.bing.net/th?id=OIP.C4vvjQgPzPD3IrOHEZsQ7AAAAA&pid=Api&P=0&w=169&h=168')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholars', to='piggy.room')),
            ],
        ),
    ]
