# Generated by Django 4.0.6 on 2022-07-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='date_Of_Birth',
            field=models.DateField(default='2012-11-12', max_length=10),
        ),
    ]
