# Generated by Django 4.0.6 on 2022-07-06 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='piggy.scholar')),
            ],
        ),
    ]
