# Generated by Django 4.0.6 on 2022-07-08 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0002_alter_scholar_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholar', to='piggy.room'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Jon', max_length=50)),
                ('last_name', models.CharField(default='Doe', max_length=50)),
                ('scholar_name', models.CharField(default='Jon Doe', max_length=50)),
                ('relation_To_Scholar', models.CharField(default='mother', max_length=10)),
                ('phone_number', models.CharField(default='(516)123-4567', max_length=10)),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='piggy.scholar')),
            ],
        ),
    ]
