# Generated by Django 4.0.6 on 2022-07-08 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0003_alter_scholar_room_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='scholar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='piggy.scholar'),
        ),
    ]
