# Generated by Django 4.0.6 on 2022-07-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0003_room_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='scholar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='piggy.scholar'),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='Room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scholar', to='piggy.room'),
        ),
    ]
