# Generated by Django 4.0.6 on 2022-07-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0004_alter_parent_scholar_alter_scholar_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='parent_Number',
            field=models.CharField(default='(516)123-4567', max_length=25),
        ),
    ]
