# Generated by Django 4.0.6 on 2022-07-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0007_room_scholar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='grade_level',
            field=models.CharField(default='4', max_length=4),
        ),
    ]
