# Generated by Django 4.0.6 on 2022-07-19 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0008_room_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='scholar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent_scholar', to='piggy.scholar'),
        ),
    ]
