# Generated by Django 4.0.6 on 2022-07-20 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0010_alter_scholar_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='Room',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='piggy.room'),
        ),
    ]
