# Generated by Django 4.0.6 on 2022-07-20 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0012_alter_scholar_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='scholar',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='parent_scholar', to='piggy.scholar'),
        ),
    ]
