# Generated by Django 4.0.6 on 2022-07-20 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0013_alter_parent_scholar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholar',
            name='Room',
        ),
        migrations.AddField(
            model_name='scholar',
            name='room',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='piggy.room'),
        ),
    ]
