# Generated by Django 4.0.6 on 2022-07-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0014_remove_scholar_room_scholar_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='Friday',
            field=models.TextField(default='How will your scholar get home today?'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Monday',
            field=models.TextField(default='How will your scholar get home today?'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Thursday',
            field=models.TextField(default='How will your scholar get home today?'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Tuesday',
            field=models.TextField(default='How will your scholar get home today?'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Wednesday',
            field=models.TextField(default='How will your scholar get home today?'),
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='room',
        ),
        migrations.AddField(
            model_name='scholar',
            name='room',
            field=models.ManyToManyField(to='piggy.room'),
        ),
    ]
