# Generated by Django 4.0.6 on 2022-07-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0015_scholar_friday_scholar_monday_scholar_thursday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='photo_url',
            field=models.TextField(default='https://tse1.mm.bing.net/th?id=OIP.o-paU20ODu6RRuU9ZIMCcQHaHa&pid=Api&P=0'),
        ),
    ]
