# Generated by Django 4.0.6 on 2022-07-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0018_remove_scholar_friday_remove_scholar_monday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='pickup_Method',
            field=models.CharField(default='Let us know if there will be any changes this week!', max_length=250),
        ),
    ]
