# Generated by Django 4.0.6 on 2022-07-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggy', '0020_alter_room_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='photo_url',
            field=models.TextField(default='https://tse4.mm.bing.net/th?id=OIP.cWbcRfqUGcdv-ISD0FGlMwHaHq&pid=Api&P=0'),
        ),
    ]
